# Generated by Django 4.2.26 on 2026-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_service', '0007_backfill_scd_source_location_authorizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddelivery',
            name='sales_order_object_id',
            field=models.CharField(blank=True, help_text='SAP ByD ObjectID of the Sales Order', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inbounddelivery',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inbounddelivery',
            name='object_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inbounddelivery',
            name='sales_order_reference',
            field=models.CharField(blank=True, db_index=True, help_text='SAP ByD Sales Order ID - what the store receives against', max_length=50, null=True),
        ),
    ]
